/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Real_Estate;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sahil
 */
public class Home_Details extends javax.swing.JFrame {

    /**
     * Creates new form Home_Details
     */
    Connection con = null;

    public Home_Details(){
        initComponents();
        con = DB.dbconnect();
    }
    String h_id,h=null,s,r;
    public Home_Details(String h_id,String s,String r){
        initComponents();
        con = DB.dbconnect();
        //JOptionPane.showMessageDialog(null, h_id);
        this.s = s;
        this.r = r;
        this.h_id=h_id;
        h=h_id;
        jl1.setText("House : "+h_id);
        jl1.setFont(new Font("Sitka Small", Font.BOLD, 18));
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Payment");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jl1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jButton1)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(70, 70, 70))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                try
        {
            int a;
            PreparedStatement pst = con.prepareStatement("select * from home where Home_id=?");
            pst.setString(1, h);
            String t;
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rd = rs.getMetaData();
            a=rd.getColumnCount();
            System.out.println(a);
            int i=0;
            int j=108;
            int k=0;
            while(rs.next())
            {
                JLabel l4 = new JLabel();
                add(l4);
                setLayout(null);
                l4.setBounds(50,i+125,250,120);
                Image getAbsolutePath = null;
                ImageIcon icon = new ImageIcon(rs.getString("Property_Card"));
                Image image = icon.getImage().getScaledInstance(l4.getWidth(),l4.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image3 = new ImageIcon(image);
                l4.setIcon(image3);
                //System.out.println(l4.getWidth()+" "+l4.getHeight());
                
               
                JLabel l1,l2,l3,l6,l5,l7,l8,l9,l10,l11,l12,l13,l14;
               
                l1 = new JLabel("House Id :");
                add(l1);
                l1.setBounds(330,j+20,100,20);
                l1.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l7 = new JLabel(rs.getString("Home_id"));
                h_id = rs.getString("Home_id");
                add(l7);
                l7.setBounds(k+450,j+20,100,20);
                l7.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                System.out.println("abc");
                j+=30;
                l2 = new JLabel("Area :");
                add(l2);
                l2.setBounds(k+330,j+20,100,20);
                l2.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l8 = new JLabel(rs.getString("Area"));
                add(l8);
                l8.setBounds(k+450,j+20,100,20);
                l8.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                j+=30;
                l3=new JLabel();
                if(r.equals("Buyer"))
                {
                    l3 = new JLabel("Price :");
                }
                else if(r.equals("Tenants"))
                {
                    l3 = new JLabel("Rent :");
                }
                add(l3);
                l3.setBounds(k+330,j+20,100,20);
                l3.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l9 = new JLabel();
                if(r.equals("Buyer"))
                {
                    l9 = new JLabel(rs.getString("Price"));
                }
                else if(r.equals("Tenants"))
                {
                    l9 = new JLabel(rs.getString("Rent"));
                }
                add(l9);
                l9.setBounds(k+450,j+20,100,20);
                l9.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                j+=30;
                l5 = new JLabel("Location :");
                add(l5);
                l5.setBounds(k+330,j+20,100,20);
                l5.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l10 = new JLabel(rs.getString("Location"));
                add(l10);
                l10.setBounds(k+450,j+20,100,20);
                l10.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                j+=30;
                l5 = new JLabel("Landmark :");
                add(l5);
                l5.setBounds(k+330,j+20,100,20);
                l5.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l12 = new JLabel(rs.getString("Landmarks"));
                add(l12);
                l12.setBounds(k+450,j+20,800,20);
                l12.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                j+=30;
                l13 = new JLabel("Seller :");
                add(l13);
                l13.setBounds(k+330,j+20,100,20);
                l13.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l14 = new JLabel(rs.getString("Seller"));
                add(l14);
                l14.setBounds(k+450,j+20,100,20);
                l14.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
            }
        }
        catch(SQLException e){}
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Payment p = new Payment(this.h,s,r);
        p.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    class Handler implements ActionListener
    {
        String h;
        public Handler(){}
        public Handler(String h)
        {
           this.h=h; 
        }
        public void actionPerformed(ActionEvent e)
        {
            Home_Details h = new Home_Details(this.h,s,r);
            h.setVisible(true);
            //JOptionPane.showMessageDialog(null, "test");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home_Details().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Home_Details.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jl1;
    // End of variables declaration//GEN-END:variables
}
