/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Real_Estate;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author dell
 */
public class Interior_Home_design extends javax.swing.JFrame {

    /**
     * Creates new form Interior_Home_design
     */
    public Interior_Home_design() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\Initial_Home_1.png");
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(Draft.getWidth(), Draft.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage = new ImageIcon(imgScale);
        Draft.setIcon(scaleImage);
    
        ImageIcon icon1 = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\Bed.png");
        Image image1 = icon1.getImage();
        Image imgScale1 = image1.getScaledInstance(Bed.getWidth(), Bed.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage1 = new ImageIcon(imgScale1);
        Bed.setIcon(scaleImage1);
        
        ImageIcon icon2 = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\Cupboard.png");
        Image image2 = icon2.getImage();
        Image imgScale2 = image2.getScaledInstance(Cupboard.getWidth(), Cupboard.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage2 = new ImageIcon(imgScale2);
        Cupboard.setIcon(scaleImage2);
        
        ImageIcon icon3 = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\Study_Table.png");
        Image image3 = icon3.getImage();
        Image imgScale3 = image3.getScaledInstance(Study_Table.getWidth(), Study_Table.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage3 = new ImageIcon(imgScale3);
        Study_Table.setIcon(scaleImage3);
        
        ImageIcon icon4 = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\Study_chair.png");
        Image image4 = icon4.getImage();
        Image imgScale4 = image4.getScaledInstance(Study_Chair.getWidth(), Study_Chair.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage4 = new ImageIcon(imgScale4);
        Study_Chair.setIcon(scaleImage4);
        
        ImageIcon icon5 = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\Small_Table.png");
        Image image5 = icon5.getImage();
        Image imgScale5 = image5.getScaledInstance(Small_table.getWidth(), Small_table.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage5 = new ImageIcon(imgScale5);
        Small_table.setIcon(scaleImage5);
        
        ImageIcon icon6 = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\Long_chair.png");
        Image image6 = icon6.getImage();
        Image imgScale6 = image6.getScaledInstance(Long_Chair.getWidth(), Long_Chair.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage6 = new ImageIcon(imgScale6);
        Long_Chair.setIcon(scaleImage6);
        
        ImageIcon icon7 = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\AC.png");
        Image image7 = icon7.getImage();
        Image imgScale7 = image7.getScaledInstance(AC.getWidth(), AC.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage7 = new ImageIcon(imgScale7);
        AC.setIcon(scaleImage7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Draft = new javax.swing.JLabel();
        Bed = new javax.swing.JLabel();
        Cupboard = new javax.swing.JLabel();
        Study_Table = new javax.swing.JLabel();
        Study_Chair = new javax.swing.JLabel();
        Small_table = new javax.swing.JLabel();
        Long_Chair = new javax.swing.JLabel();
        AC = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Design Your Home before Buy");

        Draft.setText("Draft");

        Bed.setText("Bed");
        Bed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BedMouseClicked(evt);
            }
        });

        Cupboard.setText("Cupboard");
        Cupboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CupboardMouseClicked(evt);
            }
        });

        Study_Table.setText("Study Table");
        Study_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Study_TableMouseClicked(evt);
            }
        });

        Study_Chair.setText("Study Chair");
        Study_Chair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Study_ChairMouseClicked(evt);
            }
        });

        Small_table.setText("Small table");
        Small_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Small_tableMouseClicked(evt);
            }
        });

        Long_Chair.setText("Long Chair");
        Long_Chair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Long_ChairMouseClicked(evt);
            }
        });

        AC.setText("AC");
        AC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACMouseClicked(evt);
            }
        });

        jLabel2.setText("BED");

        jLabel3.setText("CupBoard");

        jLabel4.setText("Study Table");

        jLabel5.setText("Study Chair");

        jLabel6.setText("Small Table");

        jLabel7.setText("Long Chair");

        jLabel8.setText("AC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Draft, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(91, 91, 91)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cupboard, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bed, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Study_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Study_Chair, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Small_table, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Long_Chair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Bed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 133, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Cupboard, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Study_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Study_Chair, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addComponent(Small_table, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Long_Chair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Draft, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BedMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\no_cupboard.png");
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(Draft.getWidth(), Draft.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage = new ImageIcon(imgScale);
        Draft.setIcon(scaleImage);
    }//GEN-LAST:event_BedMouseClicked

    private void CupboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CupboardMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\no_Study_table.png");
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(Draft.getWidth(), Draft.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage = new ImageIcon(imgScale);
        Draft.setIcon(scaleImage);
    }//GEN-LAST:event_CupboardMouseClicked

    private void Study_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Study_TableMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\no_Study_Chair.png");
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(Draft.getWidth(), Draft.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage = new ImageIcon(imgScale);
        Draft.setIcon(scaleImage);
    }//GEN-LAST:event_Study_TableMouseClicked

    private void Study_ChairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Study_ChairMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\no_table_near_bed.png");
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(Draft.getWidth(), Draft.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage = new ImageIcon(imgScale);
        Draft.setIcon(scaleImage);
    }//GEN-LAST:event_Study_ChairMouseClicked

    private void Small_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Small_tableMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\no_L_Chair.png");
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(Draft.getWidth(), Draft.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage = new ImageIcon(imgScale);
        Draft.setIcon(scaleImage);
    }//GEN-LAST:event_Small_tableMouseClicked

    private void Long_ChairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Long_ChairMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\no_AC.png");
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(Draft.getWidth(), Draft.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage = new ImageIcon(imgScale);
        Draft.setIcon(scaleImage);
    }//GEN-LAST:event_Long_ChairMouseClicked

    private void ACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACMouseClicked
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("C:\\Users\\dell\\Pictures\\Screenshots\\OOSD_Home_Design\\Final_Home_1.png");
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(Draft.getWidth(), Draft.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleImage = new ImageIcon(imgScale);
        Draft.setIcon(scaleImage);
    }//GEN-LAST:event_ACMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interior_Home_design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interior_Home_design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interior_Home_design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interior_Home_design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interior_Home_design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AC;
    private javax.swing.JLabel Bed;
    private javax.swing.JLabel Cupboard;
    private javax.swing.JLabel Draft;
    private javax.swing.JLabel Long_Chair;
    private javax.swing.JLabel Small_table;
    private javax.swing.JLabel Study_Chair;
    private javax.swing.JLabel Study_Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
