/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Real_Estate;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sahil
 */
public class Prioritized_View extends javax.swing.JFrame {

    /**
     * Creates new form Prioritized_View
     */
    Connection con = null;
    String s,hl,h2,h3,h_id,p;
    String[] words = new String[4];
    String r;
    String[] area = new String[4];
    public Prioritized_View(String s,String hl,String h2,String h3,String r,String p) {
        initComponents();
        con = DB.dbconnect();
        this.p = p;
        this.s = s;
        this.hl = hl;
        words=hl.split("\\s");
        this.h2=h2;
        this.r = r;
        this.h3 = h3;
        area=h3.split("\\s");
        System.out.println(area[0]);
        System.out.println(area[1]);
        
        setSize(1600,719);
        setTitle("View Houses");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setVisible(true);
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        setLocation(x, y);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        jLabel2.setText("View Houses");

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(573, 573, 573)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(618, 618, 618)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(847, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {
            int c = Integer.parseInt(words[1]);
            int d = Integer.parseInt(words[3]);
            int c1 = Integer.parseInt(area[0]);
            int d1 = Integer.parseInt(area[2]);
            System.out.println(c1+" "+d1);
            PreparedStatement pst;
            JOptionPane.showMessageDialog(this, s+" "+words[1]+" "+words[3]);
            int a;
           
            pst = con.prepareStatement("select * from home where Price between ? and ? and Location=? and Area between ? and ?");
            if(p.equals("Tenants")){
                pst = con.prepareStatement("select * from home where Rent between ? and ? and Location=? and Area between ? and ?");}
            
            pst.setInt(1, c);
            pst.setInt(2, d);
            pst.setString(3, h2);
            pst.setInt(4, c1);
            pst.setInt(5, d1);
            String t;
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rd = rs.getMetaData();
            a=rd.getColumnCount();
            System.out.println(a);
            int i=0;
            int j=104;
            int l=0;
            int k=0;
            
            JOptionPane.showMessageDialog(this, s);
            while(rs.next())
            {
                int cnt=0;
                String prio1[] = new String[6];
                prio1 = rs.getString("Landmarks").split(",");
                for(int y=0;y<prio1.length;y++)
                {
                    System.out.println(prio1[y]);
                    if(s.contains(prio1[y]))
                       cnt++;
                }
                System.out.println(cnt+" "+prio1.length);
                if(cnt==prio1.length)
                {
                    System.out.println(cnt);
                    JLabel l4 = new JLabel();
                    add(l4);
                    setLayout(null);
                    l4.setBounds(k+50,i+125,250,120);
                    Image getAbsolutePath = null;
                    ImageIcon icon = new ImageIcon(rs.getString("Property_Card"));
                    Image image = icon.getImage().getScaledInstance(l4.getWidth(),l4.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon image3 = new ImageIcon(image);
                    l4.setIcon(image3);
                    //System.out.println(l4.getWidth()+" "+l4.getHeight());


                    JLabel l1,l2,l3,l6,l5,l7,l8,l9,l10,l11,l12;

                    l1 = new JLabel("House Id :");
                    add(l1);
                    l1.setBounds(k+330,j+20,100,20);
                    l1.setFont(new Font("Sitka Small", Font.BOLD, 16));

                    l7 = new JLabel(rs.getString("Home_id"));
                    h_id = rs.getString("Home_id");
                    add(l7);
                    l7.setBounds(k+450,j+20,100,20);
                    l7.setFont(new Font("Sitka Small", Font.PLAIN, 16));

                    System.out.println("abc");
                    j+=30;
                    l2 = new JLabel("Area :");
                    add(l2);
                    l2.setBounds(k+330,j+20,100,20);
                    l2.setFont(new Font("Sitka Small", Font.BOLD, 16));

                    l8 = new JLabel(rs.getString("Area"));
                    add(l8);
                    l8.setBounds(k+450,j+20,100,20);
                    l8.setFont(new Font("Sitka Small", Font.PLAIN, 16));

                    j+=30;
                    l3=new JLabel();
                    if(p.equals("Buyer"))
                    {
                        l3 = new JLabel("Price :");
                    }
                    else if(p.equals("Tenants"))
                    {
                        l3 = new JLabel("Rent :");
                    }
                    add(l3);
                    l3.setBounds(k+330,j+20,100,20);
                    l3.setFont(new Font("Sitka Small", Font.BOLD, 16));

                    l9 = new JLabel();
                    if(p.equals("Buyer"))
                    {
                        l9 = new JLabel(rs.getString("Price"));
                    }
                    else if(p.equals("Tenants"))
                    {
                        l9 = new JLabel(rs.getString("Rent"));
                    }
                    add(l9);
                    l9.setBounds(k+450,j+20,100,20);
                    l9.setFont(new Font("Sitka Small", Font.PLAIN, 16));

                    j+=30;
                    l5 = new JLabel("Location :");
                    add(l5);
                    l5.setBounds(k+330,j+20,100,20);
                    l5.setFont(new Font("Sitka Small", Font.BOLD, 16));

                    l10 = new JLabel(rs.getString("Location"));
                    add(l10);
                    l10.setBounds(k+450,j+20,100,20);
                    l10.setFont(new Font("Sitka Small", Font.PLAIN, 16));

                    j+=30;
    //                l5 = new JLabel("Landmark :");
    //                jPanel2.add(l5);
    //                l5.setBounds(k+330,j+20,100,20);
    //                l5.setFont(new Font("Sitka Small", Font.BOLD, 16));
    //                
    //                l12 = new JLabel(rs.getString("Landmarks"));
    //                jPanel2.add(l12);
    //                l12.setBounds(k+450,j+20,200,20);
    //                l12.setFont(new Font("Sitka Small", Font.PLAIN, 16));

                    JButton b = new JButton("Show Details");
                    add(b);
                    b.setBounds(k+75,i+260,200,20);
                    Handler h1 = new Handler(rs.getString("Home_id"));
                    b.addActionListener(h1);
                    b.setFont(new Font("Sitka Small", Font.BOLD, 16));

                    b.setBackground(Color.black);
                    b.setOpaque(true);
                    b.setForeground(Color.blue);
                    b.setBorderPainted(true);
                    //b.setContentAreaFilled(false);
                    b.setSize(200, 25);

                    l++;
                    if(l%2==0)
                    {
                        j+=120;
                        i=i+240;
                        k=0;
                    }
                    else
                    {
                        k=k+650;
                        j=j-120;
                        //i=0
                    }

                }
            }
        }
        catch(SQLException e){}
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        After_Login a = new After_Login(r,p);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    class Handler implements ActionListener
    {
        String h;
        public Handler(){}
        public Handler(String h)
        {
           this.h=h; 
        }
        public void actionPerformed(ActionEvent e)
        {
            Home_Details h = new Home_Details(this.h,r,p);
            h.setVisible(true);
            //JOptionPane.showMessageDialog(null, "test");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prioritized_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prioritized_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prioritized_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prioritized_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prioritized_View("a","b","c","d","e","f").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
