/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Real_Estate;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.event.CaretEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sahil
 */
public class View_Houses2 extends javax.swing.JFrame {
    String h_id;
    /**
     * Creates new form Dynamic
     */
    String r;
    
    Connection con = null;
    String s;
    public View_Houses2(String r,String s) {
        initComponents();
        con = DB.dbconnect();
        this.s = s;
        //viewinfo.setVisible(false);
        this.r = r;
        setSize(1600,719);
        setTitle("View Houses");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setVisible(true);
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        setLocation(x, y);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(914, 220));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        jLabel2.setText("View Houses");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(522, 522, 522)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1610, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(1750, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {
            int a;
            PreparedStatement pst = con.prepareStatement("select * from home");
            String t;
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rd = rs.getMetaData();
            a=rd.getColumnCount();
            System.out.println(a);
            int i=0;
            int j=108;
            int l=0;
            int k=0;
            int cnt=0;
            while(rs.next())
            {
                JLabel l4 = new JLabel();
                jPanel2.add(l4);
                setLayout(null);
                l4.setBounds(k+50,i+125,250,120);
                Image getAbsolutePath = null;
                ImageIcon icon = new ImageIcon(rs.getString("Property_Card"));
                Image image = icon.getImage().getScaledInstance(l4.getWidth(),l4.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon image3 = new ImageIcon(image);
                l4.setIcon(image3);
                //System.out.println(l4.getWidth()+" "+l4.getHeight());
                
               
                JLabel l1,l2,l3,l6,l5,l7,l8,l9,l10,l11,l12,l13,l14;
               
                l1 = new JLabel("House Id :");
                jPanel2.add(l1);
                l1.setBounds(k+330,j+20,100,20);
                l1.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l7 = new JLabel(rs.getString("Home_id"));
                h_id = rs.getString("Home_id");
                jPanel2.add(l7);
                l7.setBounds(k+450,j+20,100,20);
                l7.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                System.out.println("abc");
                j+=30;
                l2 = new JLabel("Area :");
                jPanel2.add(l2);
                l2.setBounds(k+330,j+20,100,20);
                l2.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l8 = new JLabel(rs.getString("Area"));
                jPanel2.add(l8);
                l8.setBounds(k+450,j+20,100,20);
                l8.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                j+=30;
                l3=new JLabel();
                if(s.equals("Buyer"))
                {
                    l3 = new JLabel("Price :");
                }
                else if(s.equals("Tenants"))
                {
                    l3 = new JLabel("Rent :");
                }
                jPanel2.add(l3);
                l3.setBounds(k+330,j+20,100,20);
                l3.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l9 = new JLabel();
                if(s.equals("Buyer"))
                {
                    l9 = new JLabel(rs.getString("Price"));
                }
                else if(s.equals("Tenants"))
                {
                    l9 = new JLabel(rs.getString("Rent"));
                }
                
                jPanel2.add(l9);
                l9.setBounds(k+450,j+20,100,20);
                l9.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                j+=30;
                l5 = new JLabel("Location :");
                jPanel2.add(l5);
                l5.setBounds(k+330,j+20,100,20);
                l5.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l10 = new JLabel(rs.getString("Location"));
                jPanel2.add(l10);
                l10.setBounds(k+450,j+20,100,20);
                l10.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                j+=30;
                l13 = new JLabel("Seller :");
                jPanel2.add(l13);
                l13.setBounds(k+330,j+20,100,20);
                l13.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                l14 = new JLabel(rs.getString("Seller"));
                jPanel2.add(l14);
                l14.setBounds(k+450,j+20,100,20);
                l14.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                //j+=30;
//                l5 = new JLabel("Landmark :");
//                jPanel2.add(l5);
//                l5.setBounds(k+330,j+20,100,20);
//                l5.setFont(new Font("Sitka Small", Font.BOLD, 16));
//                
//                l12 = new JLabel(rs.getString("Landmarks"));
//                jPanel2.add(l12);
//                l12.setBounds(k+450,j+20,200,20);
//                l12.setFont(new Font("Sitka Small", Font.PLAIN, 16));
                
                JButton b = new JButton("Show Details");
                jPanel2.add(b);
                b.setBounds(k+75,i+260,200,20);
                Handler h1 = new Handler(rs.getString("Home_id"));
                b.addActionListener(h1);
                b.setFont(new Font("Sitka Small", Font.BOLD, 16));
                
                b.setBackground(Color.black);
                b.setOpaque(true);
                b.setForeground(Color.blue);
                b.setBorderPainted(true);
                //b.setContentAreaFilled(false);
                b.setSize(200, 25);
                
                l++;
                if(l%2==0)
                {
                    j+=120;
                    i=i+240;
                    k=0;
                }
                else
                {
                    k=k+650;
                    j=j-120;
                    //i=0
                }
                cnt++;
            }
        }
        catch(SQLException e){}
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        After_Login a = new After_Login(r,s);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    class Handler implements ActionListener
    {
        String h;
        public Handler(){}
        public Handler(String h)
        {
           this.h=h; 
        }
        public void actionPerformed(ActionEvent e)
        {
            Home_Details h = new Home_Details(this.h,r,s);
            h.setVisible(true);
            //JOptionPane.showMessageDialog(null, "test");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Houses2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Houses2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Houses2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Houses2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View_Houses2 a = new View_Houses2("sahil","Buyer");
                a.setSize(1600,719);
                a.setTitle("View Houses");
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                a.setVisible(true);
                int w = a.getSize().width;
                int h = a.getSize().height;
                int x = (dim.width-w)/2;
                int y = (dim.height-h)/2;
                a.setLocation(x, y);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
